spring:

  datasource:
    url: jdbc:h2:file:./src/main/resources/db/h2.database
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

