spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./db/h2.database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:h2:file:./db/h2.database
    user: sa
    password: password
    schemas: PUBLIC
    baseline-on-migrate: true


