name: Java CD with maven

on:
  pull_request:
    branches: [ release ]
    
jobs:
  build:
    uses: ./.github/workflows/build-job.yml 
  deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest ]
    steps:
            
      - name: Building the jar
        run: mkdir staging && cp target/*.jar staging
