name: Java CD with maven

on:
  pull_request:
    branches: [ release ]
    
jobs:
  deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest ]
    steps:
      - name: Executing the build-job
        uses: ./.github/workflows/build-job.yml
      
      - name: Building the jar
        run: mkdir staging && cp target/*.jar staging
