name: Java CD with maven

on:
    branches: [ release ]
    
jobs:
  build:
  
    runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [ windows-latest, macOS-latest ]

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run the Maven verify phase 
      run: mvn verify

    - name: Building the jar
      run: mkdir staging && cp target/*.jar staging
    
    - name:
      uses: actions/upload-actifact@v3
      with:
        name: Artifact
        path: staging
